import tkinter
import webbrowser
sc=tkinter.Tk()
def bi():
	sc.configure(bg="red")
def ko():
	sc.configure(bg="yellow")
def lo():
	sc2=tkinter.Tk()
	sc2.geometry("650x1600")
	bt=tkinter.Button(sc2,text="colore yellow",command=ko)
	bt.place(x=0,y=10)
	bt1=tkinter.Button(sc2,text="colore red",command=bi)
	bt1.place(x=0,y=100)
	def ni():
		u=tkinter.Label(sc2,text="la applicatin travaill sur lenté au facebook facil")
		u.place(x=0,y=300)
	bt2=tkinter.Button(sc2,text="aide",command=ni)
	bt2.place(x=0,y=200)
	sc2.mainloop()
text=tkinter.Label(sc,text="Bonjour monsieur")
text.pack()
btn=tkinter.Button(sc,text="parametre",bg="green",command=lo)
btn.place(x=10,y=10)
def la():
	webbrowser.open("https://facebook.com")
def po():
	root=tkinter.Tk()
	root.geometry("700x1400")
	x=tkinter.Label(root,text="entre ton numero et mod pass pour entre a facebook")
	entre1=tkinter.Entry(root)
	entre1.place(x=150,y=50)
	entre2=tkinter.Entry(root)
	entre2.place(x=150,y=100)
	tt1=tkinter.Label(root,text="numero")
	tt1.place(x=20,y=50)
	tt2=tkinter.Label(root,text="mod_pass")
	tt2.place(x=20,y=100)
	x.pack()
	bo=tkinter.Button(root,text="loing",command=la)
	bo.place(x=200,y=150)
	root.configure(bg="blue")
	root.mainloop()
non=tkinter.Button(sc,text="facebook",bg="blue",command=po)
non.place(x=400,y=1300)
def go():
	webbrowser.open("https://www.whatsapp.com")
def li():
	sc3=tkinter.Tk()
	sc3.geometry("700x1600")
	sc3.configure(bg="green")
	t=tkinter.Label(sc3,text="entrer au wathsapp")
	t.pack()
	t1=tkinter.Label(sc3,text="numero")
	t1.place(x=50,y=100)
	t2=tkinter.Label(sc3,text="mote de passe")
	t2.place(x=50,y=200)
	e=tkinter.Entry(sc3)
	e.place(x=200,y=100)
	e1=tkinter.Entry(sc3)
	e1.place(x=260,y=200)
	q=tkinter.Button(sc3,text="login",command=go,bg="blue")
	q.place(x=300,y=300)
	sc3.mainloop()
b=tkinter.Button(sc,text="wathsapp",bg="blue",command=li)
b.place(x=150,y=1300)
sc.mainloop()